{
 "title": "CLOUDMQ Broker Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "{cluster=~\".+\"}"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "cloudmq_rate_in{cluster=~\"$cluster\", instance=~\".+\"}"
    }
   },
   {
    "name": "cache",
    "label": "Cache Name",
    "query": {
     "query": "caffeine_cache_hit_total{cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Publish rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_rate_in{cluster=~\"$cluster\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Dispatch rate (msg / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_rate_out{cluster=~\"$cluster\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Publish throughput (MB/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_throughput_in{cluster=~\"$cluster\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Dispatch throughput (MB/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_throughput_out{cluster=~\"$cluster\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Topics count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_topics_count{cluster=~\"$cluster\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Producers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_producers_count{cluster=~\"$cluster\", instance=~\"$instance\"}) by (instance)  ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Consumers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_consumers_count{cluster=~\"$cluster\", instance=~\"$instance\"}) by (instance)  ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages Backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_msg_backlog{cluster=~\"$cluster\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_storage_write_latency_le_0_5{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_le_1{cluster=~\"$cluster\", instance=~\"instance\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_le_5{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_le_10{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_le_20{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_le_50{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_le_100{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_le_200{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_le_1000{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(cloudmq_storage_write_latency_overflow{cluster=~\"$cluster\", instance=~\"$instance\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Publish Latency - 50pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_instance_publish_latency{cluster=~\"$cluster\", instance=~\"$instance\", quantile=\"0.5\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Publish Latency - 99pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_instance_publish_latency{cluster=~\"$cluster\", instance=~\"$instance\", quantile=\"0.99\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Publish Latency - 99.9pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_instance_publish_latency{cluster=~\"$cluster\", instance=~\"$instance\", quantile=\"0.999\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Publish Latency - Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cloudmq_instance_publish_latency{cluster=~\"$cluster\", instance=~\"$instance\", quantile=\"1.0\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "instance Cache - $cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "cache" },
  {
   "title": "Cache size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caffeine_cache_estimated_size{cluster=~\"$cluster\", instance=~\"$instance\", cache=~\"$cache\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Evictions rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_eviction_total{cluster=~\"$cluster\", instance=~\"$instance\", cache=~\"$cache\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Hits / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_hit_total{cluster=~\"$cluster\", instance=~\"$instance\", cache=~\"$cache\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Misses / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_miss_total{cluster=~\"$cluster\", instance=~\"$instance\", cache=~\"$cache\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Loads / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_loads_total{cluster=~\"$cluster\", instance=~\"$instance\", cache=~\"$cache\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Avg load latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(caffeine_cache_load_duration_seconds_sum{cluster=~\"$cluster\", instance=~\"$instance\", cache=~\"$cache\"}[1m])/idelta(caffeine_cache_load_duration_seconds_count{cluster=~\"$cluster\", instance=~\"$instance\", cache=~\"$cache\"}[1m])\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}